language: cpp
sudo: required
dist: trusty 
compiler:
- g++
os:
- linux
before_script: 
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
- g++ --version
- wget http://releases.llvm.org/5.0.0/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04.tar.xz
- tar xf clang+llvm-5.0.0-linux-x86_64-ubuntu14.04.tar.xz
- export PATH=${PWD}/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/bin:$PATH
- export LD_LIBRARY_PATH=${PWD}/clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/lib
- cmake -DLLVM_DIR=clang+llvm-5.0.0-linux-x86_64-ubuntu14.04/lib/cmake/llvm .
- sudo pip install lit
script:
- make -j4 VERBOSE=1
- lit test -v
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake 
notifications:
  email: false
